// test file
const data = [
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Jalandhar",
    area: "LPU Mall",
    status: "parked",
  },
  {
    parkingRecordId: 12,
    areaId: 8,
    vehicleClass: "Bike",
    registrationNumber: "JH-123-123-PQ",
    parkingDuration: "5",
    ownerName: "Pratik K Tiwari",
    ownerAddress: "Garhwa",
    createdTime: "2022-04-09T09:42:53.000Z",
    city: "Jalandhar",
    area: "LPU Mall",
    status: "parked",
  },
  {
    parkingRecordId: 12,
    areaId: 8,
    vehicleClass: "Bike",
    registrationNumber: "JH-123-123-PQ",
    parkingDuration: "5",
    ownerName: "Pratik K Tiwari",
    ownerAddress: "Garhwa",
    createdTime: "2022-04-09T09:42:53.000Z",
    city: "Jalandhar",
    area: "LPU Mall",
    status: "parked",
  },
  {
    parkingRecordId: 12,
    areaId: 8,
    vehicleClass: "Bike",
    registrationNumber: "JH-123-123-PQ",
    parkingDuration: "5",
    ownerName: "Pratik K Tiwari",
    ownerAddress: "Garhwa",
    createdTime: "2022-04-09T09:42:53.000Z",
    city: "Jalandhar",
    area: "LPU Mall",
    status: "parked",
  },
  {
    parkingRecordId: 12,
    areaId: 8,
    vehicleClass: "Bike",
    registrationNumber: "JH-123-123-PQ",
    parkingDuration: "5",
    ownerName: "Pratik K Tiwari",
    ownerAddress: "Garhwa",
    createdTime: "2022-04-09T09:42:53.000Z",
    city: "Jalandhar",
    area: "LPU Mall",
    status: "parked",
  },
  {
    parkingRecordId: 12,
    areaId: 8,
    vehicleClass: "Bike",
    registrationNumber: "JH-123-123-PQ",
    parkingDuration: "5",
    ownerName: "Pratik K Tiwari",
    ownerAddress: "Garhwa",
    createdTime: "2022-04-09T09:42:53.000Z",
    city: "Jalandhar",
    area: "LPU Mall",
    status: "parked",
  },
  {
    parkingRecordId: 14,
    areaId: 8,
    vehicleClass: "Bike",
    registrationNumber: "JH-123-123-PQ",
    parkingDuration: "5",
    ownerName: "Pratik K Tiwari",
    ownerAddress: "Garhwa",
    createdTime: "2022-04-09T09:47:19.000Z",
    city: "Jalandhar",
    area: "LPU Mall",
    status: "parked",
  },
  {
    parkingRecordId: 12,
    areaId: 8,
    vehicleClass: "Bike",
    registrationNumber: "JH-123-123-PQ",
    parkingDuration: "5",
    ownerName: "Pratik K Tiwari",
    ownerAddress: "Garhwa",
    createdTime: "2022-04-09T09:42:53.000Z",
    city: "Jalandhar",
    area: "LPU Mall",
    status: "free",
  },
  {
    parkingRecordId: 12,
    areaId: 8,
    vehicleClass: "Bike",
    registrationNumber: "JH-123-123-PQ",
    parkingDuration: "5",
    ownerName: "Pratik K Tiwari",
    ownerAddress: "Garhwa",
    createdTime: "2022-04-09T09:42:53.000Z",
    city: "Jalandhar",
    area: "LPU Mall",
    status: "parked",
  },
  {
    parkingRecordId: 12,
    areaId: 8,
    vehicleClass: "Bike",
    registrationNumber: "JH-123-123-PQ",
    parkingDuration: "5",
    ownerName: "Pratik K Tiwari",
    ownerAddress: "Garhwa",
    createdTime: "2022-04-09T09:42:53.000Z",
    city: "Jalandhar",
    area: "LPU Mall",
    status: "parked",
  },
  {
    parkingRecordId: 12,
    areaId: 8,
    vehicleClass: "Bike",
    registrationNumber: "JH-123-123-PQ",
    parkingDuration: "5",
    ownerName: "Pratik K Tiwari",
    ownerAddress: "Garhwa",
    createdTime: "2022-04-09T09:42:53.000Z",
    city: "Jalandhar",
    area: "LPU Mall",
    status: "parked",
  },
  {
    parkingRecordId: 12,
    areaId: 8,
    vehicleClass: "Bike",
    registrationNumber: "JH-123-123-PQ",
    parkingDuration: "5",
    ownerName: "Pratik K Tiwari",
    ownerAddress: "Garhwa",
    createdTime: "2022-04-09T09:42:53.000Z",
    city: "Jalandhar",
    area: "LPU Mall",
    status: "parked",
  },
  {
    parkingRecordId: 15,
    areaId: 9,
    vehicleClass: "Car",
    registrationNumber: "JH-123-123-PQ",
    parkingDuration: "5",
    ownerName: "Pratik K Tiwari",
    ownerAddress: "Garhwa",
    createdTime: "2022-04-09T13:21:34.000Z",
    city: "Jalandhar",
    area: "LPU Law Gate",
    status: "parked",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Jalandhar",
    area: "LPU Law Gate",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Jalandhar",
    area: "LPU Law Gate",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Jalandhar",
    area: "LPU Law Gate",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Jalandhar",
    area: "LPU Law Gate",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Jalandhar",
    area: "LPU Law Gate",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Jalandhar",
    area: "LPU Law Gate",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Jalandhar",
    area: "LPU Law Gate",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Jalandhar",
    area: "LPU Law Gate",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Jalandhar",
    area: "LPU Law Gate",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Jalandhar",
    area: "LPU Law Gate",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Jalandhar",
    area: "LPU Law Gate",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Chandigarh",
    area: "Elante Mall",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Chandigarh",
    area: "Elante Mall",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Chandigarh",
    area: "Elante Mall",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Chandigarh",
    area: "Elante Mall",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Chandigarh",
    area: "Elante Mall",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Chandigarh",
    area: "Elante Mall",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Chandigarh",
    area: "Elante Mall",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Chandigarh",
    area: "Elante Mall",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Chandigarh",
    area: "Elante Mall",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Chandigarh",
    area: "Elante Mall",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Chandigarh",
    area: "Elante Mall",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Chandigarh",
    area: "Elante Mall",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Amritsar",
    area: "Golden Temple Parking Area",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Amritsar",
    area: "Golden Temple Parking Area",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Amritsar",
    area: "Golden Temple Parking Area",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Amritsar",
    area: "Golden Temple Parking Area",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Amritsar",
    area: "Golden Temple Parking Area",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Amritsar",
    area: "Golden Temple Parking Area",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Amritsar",
    area: "Golden Temple Parking Area",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Amritsar",
    area: "Golden Temple Parking Area",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Amritsar",
    area: "Golden Temple Parking Area",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Amritsar",
    area: "Golden Temple Parking Area",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Amritsar",
    area: "Golden Temple Parking Area",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Amritsar",
    area: "Golden Temple Parking Area",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "Lalpur",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "Lalpur",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "Lalpur",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "Lalpur",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "Lalpur",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "Lalpur",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "Lalpur",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "Lalpur",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "Lalpur",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "Lalpur",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "Lalpur",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "Lalpur",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "SAIL Township",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "SAIL Township",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "SAIL Township",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "SAIL Township",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "SAIL Township",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "SAIL Township",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "SAIL Township",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "SAIL Township",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "SAIL Township",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "SAIL Township",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "SAIL Township",
    status: "free",
  },
  {
    parkingRecordId: 1,
    areaId: 7,
    vehicleClass: "Car",
    registrationNumber: "NA",
    parkingDuration: "1",
    ownerName: "NA",
    ownerAddress: "NA",
    createdTime: "2022-04-05T14:43:37.000Z",
    city: "Ranchi",
    area: "SAIL Township",
    status: "free",
  },
];
const res = [];
data.forEach((item, index) => {
  let cityIndex = -1;
  res.forEach((cityItem, index) => {
    if (cityItem.city === item.city) {
      cityIndex = index;
    }
  });
  if (cityIndex !== -1) {
    let areaIndex = -1;
    res[cityIndex].areaList.forEach((areaItem, index) => {
      if (areaItem.areaName === item.area) {
        areaIndex = index;
      }
    });
    if (areaIndex !== -1) {
      res[cityIndex].areaList[areaIndex].parkingList.push({
        index: res[cityIndex].areaList[areaIndex].parkingList.length,
        vehicleClass: item.status === "parked" ? item.vehicleClass : "NA",
        registrationNumber:
          item.status === "parked" ? item.registrationNumber : "NA",
      });
    } else {
      res[cityIndex].areaList.push({
        areaName: item.area,
        parkingList: [
          {
            index: 0,
            vehicleClass: item.status === "parked" ? item.vehicleClass : "NA",
            registrationNumber:
              item.status === "parked" ? item.registrationNumber : "NA",
          },
        ],
      });
    }
  } else {
    res.push({
      city: item.city,
      areaList: [
        {
          areaName: item.area,
          parkingList: [
            {
              index: 0,
              vehicleClass: item.status === "parked" ? item.vehicleClass : "NA",
              registrationNumber:
                item.status === "parked" ? item.registrationNumber : "NA",
            },
          ],
        },
      ],
    });
  }
});

console.log(res);
